[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200
  force = true

[[redirects]]
  from = "/api/webhook/stripe"
  to = "/.netlify/functions/stripe-webhook"
  status = 200
  force = true

[[redirects]]
  from = "/api/portal-session"
  to = "/.netlify/functions/create-portal-session"
  status = 200
  force = true

[[redirects]]
  from = "/api/cancel-subscription"
  to = "/.netlify/functions/cancel-subscription"
  status = 200
  force = true

[[redirects]]
  from = "/api/change-plan"
  to = "/.netlify/functions/change-subscription-plan"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
